services:
  lunch:
    container_name: lunch
    image: localhost/jdobes/lunch:latest
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    env_file:
      - "./.env"
  lunch-mcp:
    container_name: lunch-mcp
    image: localhost/jdobes/lunch:latest
    entrypoint: ["python3", "-m", "lunch.mcp"]
    ports:
      - "9000:9000"
