name: Build

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build
      cancel-in-progress: true
    env:
      REGISTRY: ghcr.io
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
      REPO: jdobes/lunch
      PLATFORM: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build React app
        run: |
          ./build_web.sh
      - name: Install qemu-user-static for multi-arch build
        run: |
          sudo apt update && sudo apt install -y qemu-user-static
      - name: Login to registry
        run: |
          echo "$REGISTRY_PASS" | podman login -u "$REGISTRY_USER" --password-stdin "$REGISTRY"
      - name: Build image
        run: |
          podman build --platform "$PLATFORM" --manifest lunch .
      - name: Push image
        run: |
          podman manifest push --all lunch docker://$REGISTRY/$REPO:$(git describe --abbrev=0 --tags)
          podman manifest push --all lunch docker://$REGISTRY/$REPO:latest
          podman manifest rm lunch
