name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    concurrency: release
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run python-semantic-release
      run: |
        pip install python-semantic-release
        semantic-release version
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
