name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.21.1
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        root_options: "-v -c releaserc.json"
