name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    concurrency: release
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run python-semantic-release
      run: |
        pip install python-semantic-release
        semantic-release version
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
